apiVersion: securitytower.io/v1alpha1
kind: Cluster
metadata:
    name: cluster1
spec:
    tenant: default
    configuration:
        description: this is a short description of the cluster
        geographicLocation: location
        production: false
    policies:
        path: cluster/global/policies
